
ALTER TABLE DW_BRASILEIRAO.TB_DIM_CLUBE MODIFY ( VERSAO NUMBER(5) );
ALTER TABLE DW_BRASILEIRAO.TB_DIM_CLUBE MODIFY (SK_CLUBE NUMBER(10) );


ALTER TABLE DW_BRASILEIRAO.TB_DIM_ESTADIO MODIFY (VERSAO NUMBER(5) );
ALTER TABLE DW_BRASILEIRAO.TB_DIM_ESTADIO MODIFY (SK_ESTADIO NUMBER(10) );