CREATE OR REPLACE EDITIONABLE PROCEDURE "DW_BRASILEIRAO"."SP_CARGA_FRIA_DIM_SEM_INFORMACAO" 
AS

--/**************************************************************************************
-- **
-- ** PROCEDURE PARA CARGA DAS LINHAS 'SEM INFORMAÇÃO' NAS TABELAS DAS DIMENSÕES
-- ** QUE VÃO REPRESENTAR OS RELACIONAMENTOS COM AS LINHAS DA FATO CUJA FK SEJA NULL
-- ** CASO EXISTAM
-- ** Autor      : SALOMÃO FREITAS JR.
-- ** Data       : 28/06/2022
-- **     
-- **************************************************************************************/


BEGIN

    -- ***** LINHA SEM INFORMAÇÃO - TB_DIM_CAMPEONATO - SK = -1 *****
    INSERT INTO TB_DIM_CAMPEONATO (SK_CAMPEONATO, COD_CAMPEONATO, NOME, ANO_EDICAO)
    VALUES (-1, 'XXXXXXX', 'SEM INFORMAÇÃO', 'XXXX');
    -- **************************************************************


    -- LINHA SEM INFORMAÇÃO - TB_DIM_ESQUEMA_TATICO - SK = -1 ******
    INSERT INTO TB_DIM_ESQUEMA_TATICO (SK_ESQUEMA, DESCRICAO)
    VALUES (-1, 'SEM INFORMAÇÃO');
    -- **************************************************************


    -- ****** LINHA SEM INFORMAÇÃO - TB_DIM_CLUBE - SK = -1 ******
    INSERT INTO TB_DIM_CLUBE (SK_CLUBE, COD_CLUBE, NOME, ESCUDO, CIDADE, ESTADO, SIGLA_ESTADO, REGIAO, DATA_INICIO, DATA_FIM, VERSAO)
    VALUES (-1, -1, 'SEM INFORMAÇÃO', NULL, 'XXXXXXX', 'XXXXXXX', 'XX', 'XXXXXXX', TO_DATE('01-01-1900', 'DD-MM-YYYY'), TO_DATE('31-12-2199 23:59:59', 'DD-MM-YYYY HH24:MI:SS'), 1);

    -- ALÉM DISSO, O COMPONENTE DO PENTAHO PARA DIM SCD2 EXIGE UMA LINHA COM SK = 0 (ZERO). SE ELA NÃO EXISTIR ELE INSERE, COM OS CAMPOS NULL
    INSERT INTO TB_DIM_CLUBE (SK_CLUBE, COD_CLUBE, NOME, ESCUDO, CIDADE, ESTADO, SIGLA_ESTADO, REGIAO, DATA_INICIO, DATA_FIM, VERSAO)
    VALUES (0, 0, 'SCD2', NULL, 'XXXXXXX', 'XXXXXXX', 'XX', 'XXXXXXX', TO_DATE('01-01-1900', 'DD-MM-YYYY'), TO_DATE('31-12-2199 23:59:59', 'DD-MM-YYYY HH24:MI:SS'), 1);
    -- **************************************************************

    -- LINHA SEM INFORMAÇÃO - TB_DIM_ESTADIO - SK = -1    
    INSERT INTO TB_DIM_ESTADIO (SK_ESTADIO, COD_ESTADIO, NOME, CIDADE, ESTADO, SIGLA_ESTADO, REGIAO, DATA_INICIO, DATA_FIM, VERSAO)
    VALUES (-1, -1, 'SEM INFORMAÇÃO', 'XXXXXXX', 'XXXXXXX', 'XX', 'XXXXXXX', TO_DATE('01-01-1900', 'DD-MM-YYYY'), TO_DATE('31-12-2199 23:59:59', 'DD-MM-YYYY HH24:MI:SS'), 1);

    -- ALÉM DISSO, O COMPONENTE DO PENTAHO PARA DIM SCD2 EXIGE UMA LINHA COM SK = 0 (ZERO). SE ELA NÃO EXISTIR ELE INSERE, COM OS CAMPOS NULL
    INSERT INTO TB_DIM_ESTADIO (SK_ESTADIO, COD_ESTADIO, NOME, CIDADE, ESTADO, SIGLA_ESTADO, REGIAO, DATA_INICIO, DATA_FIM, VERSAO)
    VALUES (0, 0, 'SCD2', 'XXXXXXX', 'XXXXXXX', 'XX', 'XXXXXXX', TO_DATE('01-01-1900', 'DD-MM-YYYY'), TO_DATE('31-12-2199 23:59:59', 'DD-MM-YYYY HH24:MI:SS'), 1);
    -- **************************************************************


END;